import { ArrowUpRight } from 'lucide-react';
const base = 'https://www.pragmaticnutritionist.com';
const contact = base + '/contact-us';
function LinkPill({href=contact,children}:{href?:string;children:React.ReactNode}){return <a href={href} className="pill">{children}<ArrowUpRight size={17} aria-hidden="true"/></a>}

export const moreReviews = [
  {quote:'I lost 14 kg in 12 weeks. As a working professional, I eat out every day. But Meenu gave me practical strategies that actually worked. I would recommend her to anyone wanting real, sustainable weight loss.',name:'Ankit',detail:'Weight Loss · Media Design Professional, Chennai'},
  {quote:'My PCOS symptoms improved in just 5–6 weeks. No more migraines. My menstrual health is better, acne reduced, and the plan was completely flexible around my life.\nMy foods craving reduce too.',name:'Amirtha',detail:'PCOS · Software Professional, Bengaluru'},
  {quote:"HbA1C reduced from 7.1 to 6.8 in just 4 weeks. I joined the 3 months diabetes plan with Meenu.\nI'm very happy with the results. The diet was simple and easy.",name:'Prabhakaran',detail:'Diabetes · Trichy'},
  {quote:"Meenu has been a constant guide and a major contributor to Charitha's national gold. Her nutrition strategy helped improve Charitha's PB from 27.8s to 27.02s, outperforming Olympic-level swimmers",name:'Dr. Smriti',detail:'Sports Nutrition · Homeopathy Doctor, Bangalore'}
];

export function PracticeIntroduction(){return <section className="practice-intro section" id="practice"><div className="intro-grid" data-reveal><p className="eyebrow green">Meenu Balaji · Online nutritionist in India</p><div><h2>From gut recovery<br/>to <em>peak performance.</em></h2><p className="intro-lead">Personalised plans built on real clinical expertise.</p><p>No generic charts, no extreme diets. A nutrition plan built around Indian food, your symptoms, and your goals.</p><div className="inline-actions"><LinkPill>Talk to a nutritionist</LinkPill><a className="pill outline-pill" href="https://wa.me/919790425908">WhatsApp Meenu<ArrowUpRight size={17}/></a></div></div></div><div className="practice-stats" data-reveal>{[['14+','Years of clinical experience'],['4500+','Clients'],['350+','Nutritionists trained'],['3','Countries: UK, New Zealand, India']].map(([number,label])=><div key={label}><strong>{number}</strong><p>{label}</p></div>)}</div><p className="trust-line" data-reveal>Trusted by public figures, founders, international-level athletes, and health professionals across India and internationally.</p><div className="press-strip" data-reveal><p className="eyebrow green">Featured in Indian, UK & US wellness magazines</p><img src="/images/journals.jpg" alt="Magazines featuring Meenu Balaji, including Thrive" loading="lazy" width="1146" height="128"/></div></section>}

export function AthleteStories(){return <section className="athletes section" id="performance"><div className="section-heading-row" data-reveal><div><p className="eyebrow green">Nutrition behind the effort</p><h2>Performance<br/>that <em>speaks.</em></h2></div><div className="section-heading-copy"><p>Nutrition support for athletes competing at national & international events.</p><p>Raising a young athlete?<br/>Their nutrition matters as much as their training.</p><LinkPill>Book a free discovery call</LinkPill></div></div><div className="athlete-gallery">{[1,2,3,4].map((n)=><figure key={n} className="athlete-photo photo-frame" data-reveal><img src={'/images/athlete-'+n+'.jpg'} alt={n===2?'Charitha, athlete featured by Pragmatic Nutrition':n===4?'Dhairya, athlete featured by Pragmatic Nutrition':'Athlete featured on the Pragmatic Nutrition homepage'} loading="lazy" width="650" height="800"/></figure>)}</div></section>}

export function GutChecker(){return <section className="gut-checker section" id="gut-checker"><div className="checker-image photo-frame" data-reveal><img src="/images/gut.jpg" alt="Fresh ingredients in a balanced vegetable bowl" loading="lazy" width="600" height="550"/></div><div data-reveal><p className="eyebrow green">Not sure where to start?</p><h2>A little clarity.<br/>In <em>two minutes.</em></h2><h3>Take our free 2-minute Gut Health Checker</h3><p>Get a clearer picture of areas worth exploring before booking a call.</p><LinkPill href={base+'/gut-health-checker'}>Free gut assessment</LinkPill></div></section>}

export function FullApproach(){return <section className="approach section" id="approach"><div data-reveal><p className="eyebrow green">The pragmatic way</p><h2>Why Pragmatic<br/><em>Nutrition?</em></h2><p className="approach-intro">Non-extreme. Flexible. Built for real life.</p></div><div className="approach-statements">{[
['Symptom-led, not template-led','Your symptoms tell us where to start. Bloating, fatigue, irregular cycles, poor focus. We trace these back to root causes, not just manage them on the surface.'],
['Behaviour coaching that actually holds','We work on habits, triggers, routines, and real-life constraints that determine whether nutrition works long term, not just what looks good on paper.'],
['Results that show up in daily life','Most clients notice measurable improvement in digestion, energy, metabolic markers, or symptom stability within 8–12 weeks when plans are followed consistently.'],
['Global clinical perspective, Indian execution','With clinical practice across India, the UK, and New Zealand, we apply international standards using practical Indian foods and real-world lifestyles.']
].map(([title,text])=><article key={title} data-reveal><h3>{title}</h3><p>{text}</p></article>)}<p className="results-note">Results are based on client self-reported goal achievement and vary between individuals.</p></div></section>}

export function GettingStarted(){return <section className="getting-started section" id="getting-started"><div className="section-heading-row" data-reveal><div><p className="eyebrow green">A practical way forward</p><h2>Three steps to<br/>your <em>transformation.</em></h2></div><LinkPill>Book a free call</LinkPill></div><div className="steps-list">{[
['Book a free call','Schedule a free 15 minute video call with us.'],
['Health assessment & root cause analysis','We understand your health goals, medical history and suggest the right nutrition program for you (12/24 weeks or Annual plan).'],
['Sign up & get started','Get a detailed, tailored plan covering exactly what to eat, when, and why, no generic charts. With periodic reviews and chat support.']
].map(([title,text])=><article key={title} data-reveal><span className="step-marker" aria-hidden="true"/><h3>{title}</h3><p>{text}</p></article>)}</div></section>}

export function AwardFeature(){return <section className="award-feature section" id="recognition"><div data-reveal><p className="eyebrow green">Recognition for practical care</p><h2>A practice<br/>with <em>purpose.</em></h2><h3>Best Nutritionist & Dietitian Award</h3><p>Meenu Balaji was presented with the Best Nutritionist & Dietitian Award at the Realistic Awards 2026, Chennai, alongside eminent women achievers from various fields.</p><LinkPill href="https://republicnewsindia.com/9th-edition-realistic-awards-2026-an-evening-celebrating-the-power-and-grace-of-womanhood/">Read in Republic News India</LinkPill></div><div className="award-image photo-frame" data-reveal><img src="/images/award.png" alt="Meenu Balaji at the Realistic Awards 2026 in Chennai" loading="lazy" width="1000" height="548"/></div></section>}

export const extraServices=[['Child & Teen Nutrition','/child-nutritionist-india'],['Signature Nutrition Program','/signature-nutrition-program'],['ADHD Nutrition','/adhd-nutritionist-children'],['Diabetes Nutrition Plan','/best-diabetes-nutritionist-india']];
export function ExtendedFooter(){return <div className="extended-footer"><div className="footer-description"><p>Pragmatic Nutrition provides personalised, evidence-based nutrition support focused on Gut Health and Sports Nutrition, with additional nutrition services for diabetes, PCOS, weight management, child and teen nutrition, and ADHD.</p><p>Founded and led by Meenu Balaji, M.H.Sc Food Science & Nutrition, Pragmatic Nutrition combines 14+ years of clinical experience with practical, Indian-lifestyle-focused nutrition strategies for clients across India and internationally.</p><p>HPR ID: 99-1467-6526-4626</p></div><div className="footer-resources"><div><h3>More nutrition services</h3>{extraServices.map(([title,path])=><a href={base+path} key={path}>{title}</a>)}</div><div><h3>Learn & grow</h3><a href={base+'/nutrition-plans'}>Nutrition plans</a><a href={base+'/online-nutrition-course'}>Courses & masterclasses</a><a href={base+'/masterclass-nutrition-private-practice'}>Build your private practice</a><a href={base+'/nutritionist-certificate-courses'}>Online certificate courses for nutritionists</a><a href={contact}>Contact us</a></div></div><p className="service-locations">Online consultations available across India and internationally. Major service locations: Chennai, Bengaluru, Hyderabad, Mumbai, Delhi NCR, Pune, Coimbatore, Kochi, Trivandrum, Madurai, Trichy, Salem, UK, Canada, Australia, New Zealand and Ireland.</p><div className="social-links">{[['YouTube','https://www.youtube.com/@pragmaticnutrition'],['WhatsApp','https://wa.me/919790425908'],['Facebook','https://www.facebook.com/Pragmaticnutritionist'],['LinkedIn','https://www.linkedin.com/in/meenu-balaji'],['Pinterest','https://in.pinterest.com/Meenupreethibalaji/']].map(([title,url])=><a key={title} href={url}>{title}<ArrowUpRight size={13}/></a>)}</div></div>}
