import { ArrowUpRight, Globe2, Video, ClipboardCheck, Sprout, Users, GraduationCap, Activity, Timer, Award } from 'lucide-react';
const base = '';
const contact = '#contact';
function LinkPill({href=contact,children}:{href?:string;children:React.ReactNode}){return <a href={href} className="pill">{children}<ArrowUpRight size={17} aria-hidden="true"/></a>}

export const moreReviews = [
  {quote:'I lost 14 kg in 12 weeks. As a working professional, I eat out every day. But Meenu gave me practical strategies that actually worked. I would recommend her to anyone wanting real, sustainable weight loss.',name:'Ankit',detail:'Weight Loss · Media Design Professional, Chennai'},
  {quote:'My PCOS symptoms improved in just 5–6 weeks. No more migraines. My menstrual health is better, acne reduced, and the plan was completely flexible around my life.\nMy foods craving reduce too.',name:'Amirtha',detail:'PCOS · Software Professional, Bengaluru'},
  {quote:"HbA1C reduced from 7.1 to 6.8 in just 4 weeks. I joined the 3 months diabetes plan with Meenu.\nI'm very happy with the results. The diet was simple and easy.",name:'Prabhakaran',detail:'Diabetes · Trichy'},
  {quote:"Meenu has been a constant guide and a major contributor to Charitha's national gold. Her nutrition strategy helped improve Charitha's PB from 27.8s to 27.02s, outperforming Olympic-level swimmers",name:'Dr. Smriti',detail:'Sports Nutrition · Homeopathy Doctor, Bangalore'}
];

export function PracticeIntroduction(){const stats=[{number:'14+',label:'Years of clinical experience',Icon:Activity},{number:'4500+',label:'Clients',Icon:Users},{number:'350+',label:'Nutritionists trained',Icon:GraduationCap},{number:'3',label:'Countries of clinical practice',detail:'UK · New Zealand · India',Icon:Globe2}];return <section className="practice-intro section" id="practice"><div className="practice-proof" data-reveal><div className="practice-proof-heading"><span>Clinical experience, in numbers.</span><span className="practice-proof-line"/></div><div className="practice-proof-grid">{stats.map(({number,label,detail,Icon})=><div className="practice-proof-stat" key={label}><div className="practice-stat-top"><strong>{number}</strong><span className="practice-stat-icon"><Icon size={18} strokeWidth={1.5} aria-hidden="true"/></span></div><p>{label}</p>{detail&&<span className="practice-stat-detail">{detail}</span>}</div>)}</div></div><div className="practice-press" data-reveal><div className="press-loop" aria-label="Publications featuring Meenu Balaji" tabIndex={0}><div className="press-loop-track"><div className="press-logo-list"><div className="press-logo press-indian"><img src="/images/press/indian-express.webp" alt="The Indian Express" loading="lazy" width="256" height="256"/></div><div className="press-logo press-authority"><img src="/images/press/authority-magazine.jpg" alt="Authority Magazine" loading="lazy" width="400" height="208"/></div><div className="press-logo press-thrive"><img src="/images/press/thrive.jpg" alt="Thrive Health and Nutrition Magazine" loading="lazy" width="300" height="155"/></div><div className="press-logo press-shefinds"><img src="/images/press/shefinds.png" alt="SheFinds" loading="lazy" width="190" height="66"/></div></div><div className="press-logo-list" aria-hidden="true"><div className="press-logo press-indian"><img src="/images/press/indian-express.webp" alt="The Indian Express" loading="lazy" width="256" height="256"/></div><div className="press-logo press-authority"><img src="/images/press/authority-magazine.jpg" alt="Authority Magazine" loading="lazy" width="400" height="208"/></div><div className="press-logo press-thrive"><img src="/images/press/thrive.jpg" alt="Thrive Health and Nutrition Magazine" loading="lazy" width="300" height="155"/></div><div className="press-logo press-shefinds"><img src="/images/press/shefinds.png" alt="SheFinds" loading="lazy" width="190" height="66"/></div></div></div></div></div></section>}

export function AthleteStories(){const athletes=[{image:1,sport:'Jiu-Jitsu',name:'Sai Ameya',achievements:['Gold medal, IBJJF, Kuala Lumpur International Open'],alt:'Sai Ameya on the podium at the Kuala Lumpur International Open'},{image:2,sport:'Swimming',name:'Charitha Phanindranath',achievements:['U17 national record holder — 50m freestyle, 26.04s'],alt:'Charitha Phanindranath holding her swimming medal'},{image:3,sport:'Squash',name:'Aahana Singh',achievements:['GU17 Champion — Bengal Junior Open 2026'],alt:'Aahana Singh receiving her squash trophy'},{image:4,sport:'UIPM-Pentathlon',name:'Dhairya Samahita Naveen',achievements:['2025 silver medal holder at the International Championship'],alt:'Dhairya Samahita Naveen at a national biathle event'}];return <section className="athletes section" id="performance"><div className="performance-heading" data-reveal><div><h2>Performance<br/>that <em>speaks.</em></h2><p className="athlete-section-intro">Nutrition support for athletes competing at national &amp; international events.</p></div></div><div className="athlete-spotlight">{athletes.map(a=><figure key={a.image} className="spotlight-card" data-reveal><div className="athlete-card-photo"><img src={'/images/athlete-'+a.image+'.jpg'} alt={a.alt} loading="lazy" width={a.image===3?440:650} height={a.image===3?540:800}/></div><figcaption><span className="athlete-sport-label">{a.sport}</span><h3>{a.name}</h3><div className="athlete-achievements">{a.achievements.map(achievement=><p key={achievement}>{achievement}</p>)}</div></figcaption></figure>)}</div><div className="performance-invitation" data-reveal><div className="performance-invitation-mark" aria-hidden="true"><ArrowUpRight size={30}/></div><div><h3>Raising a young athlete?</h3><p>Their nutrition matters as much as their training.</p></div><LinkPill>Book a free discovery call</LinkPill></div></section>}


export function GutChecker(){return <section className="gut-checker section" id="gut-checker"><div className="checker-feature" data-reveal><div className="checker-copy"><span className="checker-time"><Timer size={16} strokeWidth={1.5}/>2 minutes · Free assessment</span><h2>A little clarity.<br/>A <em>healthier beginning.</em></h2><p className="checker-description">Take our free Gut Health Checker. Get a clearer picture of areas worth exploring before booking a call.</p><LinkPill href={base+'/gut-health-checker'}>Check your gut health</LinkPill></div><div className="checker-visual"><img src="/images/gut-checker-generated.webp" alt="Yogurt with berries and oats, papaya, ginger, lentils and mint on a sunlit kitchen table" loading="lazy" width="1000" height="1250"/></div></div></section>}

export function FullApproach(){const images=[['digestion','Yogurt, papaya, ginger and oats on a light kitchen table','Principle 01'],['habits','Hands preparing balanced lunches in reusable glass containers','Principle 02'],['wellbeing','Fruit, walking shoes and a water bottle beside a sunny window','Principle 03'],['indian-meal','An Indian meal with dal, rice, chapati and vegetables','Principle 04']];return <section className="approach section" id="approach"><div className="approach-heading" data-reveal><h2>Why Pragmatic<br/><em>Nutrition?</em></h2><p className="approach-intro">Non-extreme. Flexible. Built for real life.</p></div><div className="approach-statements">{[
['Symptom-led, not template-led','Your symptoms tell us where to start. Bloating, fatigue, irregular cycles, poor focus. We trace these back to root causes, not just manage them on the surface.'],
['Behaviour coaching that actually holds','We work on habits, triggers, routines, and real-life constraints that determine whether nutrition works long term, not just what looks good on paper.'],
['Results that show up in daily life','Most clients notice measurable improvement in digestion, energy, metabolic markers, or symptom stability within 8–12 weeks when plans are followed consistently.'],
['Global clinical perspective, Indian execution','With clinical practice across India, the UK, and New Zealand, we apply international standards using practical Indian foods and real-world lifestyles.']
].map(([title,text],i)=>{return <article key={title} className="approach-card" data-reveal><div className="approach-card-photo"><img src={'/images/approach-'+images[i][0]+'.webp'} alt={images[i][1]} width="1000" height="667" loading="lazy"/><span className="approach-card-badge">{images[i][2]}</span></div><div className="approach-card-copy"><h3>{title}</h3><p>{text}</p></div></article>})}</div></section>}

export function GettingStarted(){const steps=[{title:'Let’s talk.',label:'A free first conversation',text:'Schedule a free 15-minute video call. Tell us what you want to change and ask your questions.',detail:'15 minutes · Video call',Icon:Video},{title:'Understand your body.',label:'Your health, in context',text:'We review your goals and medical history, explore root causes, and recommend the right nutrition program.',detail:'12 / 24 weeks or an annual plan',Icon:ClipboardCheck},{title:'Make it your everyday.',label:'A plan that fits your life',text:'Get a tailored plan covering what to eat, when, and why—with regular reviews and chat support.',detail:'Personalised plan · Ongoing support',Icon:Sprout}];return <section className="getting-started section" id="getting-started"><div className="journey-heading" data-reveal><h2>Small steps.<br/><em>Meaningful change.</em></h2><p className="section-description">From your first conversation to a plan that fits your everyday.</p></div><ol className="nutrition-journey">{steps.map(({title,label,text,detail,Icon},i)=><li className="journey-step" key={title} data-reveal><div className="journey-stage"><span className="journey-number">0{i+1}</span><span className="journey-icon" aria-hidden="true"><Icon size={26} strokeWidth={1.5}/></span></div><p className="journey-label">{label}</p><h3>{title}</h3><p className="journey-description">{text}</p><span className="journey-detail">{detail}</span></li>)}</ol><div className="journey-start" data-reveal><span className="journey-start-note"><span/>Your first step starts with a conversation.</span><LinkPill>Book a free call</LinkPill></div></section>}

export function AwardFeature(){return <section className="award-feature section" id="recognition"><div className="recognition-heading" data-reveal><h2>A practice<br/>with <em>purpose.</em></h2><p className="section-description">Recognition for practical, personalised nutrition care.</p></div><figure className="recognition-story" data-reveal><div className="recognition-photo"><img src="/images/recognition.avif" alt="Meenu Balaji at the Realistic Awards 2026 in Chennai" loading="lazy" width="2802" height="1536"/></div><figcaption><div className="recognition-title"><span className="recognition-medal" aria-hidden="true"><Award size={28} strokeWidth={1.4}/></span><div><h3>Best Nutritionist<br/>&amp; Dietitian Award</h3></div></div><p>Meenu Balaji was presented with the Best Nutritionist &amp; Dietitian Award at the Realistic Awards 2026, Chennai, alongside eminent women achievers from various fields.</p><LinkPill href="https://republicnewsindia.com/9th-edition-realistic-awards-2026-an-evening-celebrating-the-power-and-grace-of-womanhood/">Read the story</LinkPill></figcaption></figure></section>}

export const extraServices=[['Child & Teen Nutrition','/child-nutritionist-india'],['Signature Nutrition Program','/signature-nutrition-program'],['ADHD Nutrition','/adhd-nutritionist-children'],['Diabetes Nutrition Plan','/best-diabetes-nutritionist-india']];
export function ExtendedFooter(){return <><div className="footer-main-grid"><div className="footer-identity"><a href="#" aria-label="Pragmatic Nutrition home"><img src="/images/logo.png" alt="Pragmatic Nutrition" width="2400" height="1063"/></a><p className="footer-motto">Good science.<br/>Real food. <em>Your life.</em></p><p className="footer-summary">Personalised nutrition with Meenu Balaji. 14+ years of clinical experience.</p><span className="footer-registration">HPR ID: 99-1467-6526-4626</span></div><nav aria-label="Footer quick links"><h3>Quick links</h3><a href="#">Home</a><a href={'#about'}>About Meenu</a><a href={'#gut'}>Gut Health</a><a href={'#sports'}>Sports Nutrition</a><a href={base+'/blog'}>Blog</a><a href={contact}>Contact us</a></nav><nav aria-label="Footer nutrition services"><h3>Nutrition services</h3>{extraServices.map(([title,path])=><a href={base+path} key={path}>{title}</a>)}</nav><nav aria-label="Footer resources"><h3>Resources</h3><a href={base+'/nutrition-plans'}>Nutrition plans</a><a href={base+'/online-nutrition-course'}>Courses & masterclasses</a><a href={base+'/masterclass-nutrition-private-practice'}>Private practice masterclass</a><a href={base+'/nutritionist-certificate-courses'}>Nutritionist certificates</a></nav></div><div className="footer-contact-strip"><div><span>Email us</span><a href="mailto:meenu@pragmaticnutritionist.com">meenu@pragmaticnutritionist.com</a></div><div><span>Call us</span><a href="tel:+917550069612">+91 75500 69612</a></div><div><span>Visit by appointment</span><p>Five Furlong Road, Guindy, Chennai 600032</p></div></div><div className="footer-social-row"><p>Based in Chennai. Online consultations worldwide.</p><div>{[['Instagram','https://www.instagram.com/meenubalaji_nutritionist/'],['YouTube','https://www.youtube.com/@pragmaticnutrition'],['WhatsApp','https://wa.me/919790425908'],['Facebook','https://www.facebook.com/Pragmaticnutritionist'],['LinkedIn','https://www.linkedin.com/in/meenu-balaji'],['Pinterest','https://in.pinterest.com/Meenupreethibalaji/']].map(([title,url])=><a href={url} key={title}>{title}<ArrowUpRight size={12}/></a>)}</div></div><div className="footer-legal-row"><p>© {new Date().getFullYear()} Pragmatic Nutrition. All rights reserved.</p><div><a href={base+'/privacy-policy-1'}>Privacy policy</a><a href={base+'/terms-conditions'}>Terms & conditions</a><a href={base+'/refund-policy'}>Refund policy</a></div></div><p className="footer-medical-note"><strong>Medical disclaimer:</strong> For education only, not medical advice. Consult your healthcare professional before changing your diet. Individual results vary.</p><div className="footer-wordmark" aria-hidden="true">Pragmatic <em>Nutrition.</em></div></>}


export function FrequentlyAskedQuestions(){const questions=[
['How do I get started?','Book a free 15-minute discovery call. We’ll discuss your goals and recommend the next step for you.'],
['Are consultations available online?','Yes. Online consultations are available across India and internationally. In-person appointments are available in Chennai by appointment.'],
['Will I need to give up my usual foods?','Plans are built around Indian food, your preferences, symptoms, and everyday routine. The focus is on practical changes you can maintain, rather than extreme diets.'],
['What nutrition support do you offer?','Our main areas are gut health and sports nutrition. We also offer support for weight management, diabetes, PCOS, child and teen nutrition, and ADHD nutrition.'],
['What does a personalised program include?','Your program starts with a review of your health goals and medical history. You receive a tailored nutrition plan, with periodic reviews and chat support. Program options include 12 weeks, 24 weeks, and an annual plan.'],
['How long does it take to see progress?','Progress depends on your goals, health history, and consistency. Individual results vary. Your reviews help assess what is working and where your plan needs adjusting.']
];return <section className="faq-section section" id="faq"><div className="faq-heading" data-reveal><h2>Good questions.<br/><em>Simple answers.</em></h2><p className="section-description">What to know before starting your nutrition journey.</p></div><div className="faq-list" data-reveal>{questions.map(([question,answer],i)=><details className="faq-item" name="nutrition-faq" key={question}><summary><span className="faq-number">0{i+1}</span><span>{question}</span><span className="faq-toggle" aria-hidden="true"/></summary><div className="faq-answer"><p>{answer}</p></div></details>)}</div><div className="faq-contact" data-reveal><p>Have something else on your mind?</p><LinkPill>Ask us a question</LinkPill></div></section>}
