'use client';
import { useEffect, useRef, useState } from 'react';
import { Experience } from './experience';
import { WhatsAppWidget } from './whatsapp';
import { BookingModal } from './booking';
import { PracticeIntroduction, AthleteStories, GutChecker, FullApproach, GettingStarted, AwardFeature, FrequentlyAskedQuestions, ExtendedFooter, moreReviews, extraServices } from './content';
import { ArrowUpRight, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Menu, X, ChevronDown, Pause, Play } from 'lucide-react';
const base='';
const links={gut:'#gut',sports:'#sports',about:'#about',contact:'#contact'};
const navLinks={gut:'/best-gut-health-nutritionist-india',sports:'/sports-nutritionist-india',about:'/about-meenu-balaji-nutritionist',contact:'/contact-us'};
const slides=[{image:'hero',label:'Personalised care with Meenu Balaji',title:<>Gut health.<br/>Sports nutrition.<br/><em>Built around you.</em></>,description:'Personalised nutrition with Meenu Balaji for digestive concerns and athletic performance. Get practical guidance built around your symptoms, training, food preferences, and everyday routine.',cta:'Find your starting point',href:links.contact,alt:'Illustration of a personalised nutrition consultation in a sunlit studio'},{image:'gut',label:'A little more ease. Every day.',title:<>Gut health.<br/>Personalised <em>care.</em></>,description:'Make sense of recurring bloating, acidity, and digestive discomfort with guidance built around your symptoms and eating habits. Together, we create a practical nutrition plan that supports your gut and fits the foods you enjoy.',cta:'Explore Gut Health',href:links.gut,alt:'A creative cascade of papaya, cucumber ribbons, mint and oats above a sunlit kitchen counter'},{image:'sports',label:'Fuel your ambition.',title:<>Your effort.<br/>Better <em>fuel.</em></>,description:'Give your training the nutrition support it deserves. From everyday meals and hydration to competition preparation and recovery, build a personalised fuelling plan around your sport, schedule, and goals—with guidance for youth and competitive athletes.',cta:'Explore Sports Nutrition',href:links.sports,alt:'An athlete taking a recovery break with a balanced meal and water'}];
const disciplinesData = [
  {
    id: 'gut',
    number: '01',
    category: 'Clinical Nutrition',
    title: 'Gut Health',
    subtitle: 'Digestive & Metabolic Care',
    image: '/images/discipline-gut-premium.webp',
    alt: 'A nourishing bowl of lentils, rice, pumpkin and greens on an ivory table',
    description: 'Understand what’s driving your symptoms and build a sustainable, evidence-based nutrition program tailored to your gut microbiome.',
    tags: ['Bloating & Acidity', 'IBS & GERD', 'SIBO Protocol', 'Enzymes & Digestion', 'Food Intolerances', 'Gut-Brain Axis'],
    href: links.gut,
    cta: 'Explore Gut Health',
    meta: 'Personalised 1:1 Care'
  },
  {
    id: 'sports',
    number: '02',
    category: 'Performance Nutrition',
    title: 'Sports Nutrition',
    subtitle: 'Competitive & Youth Athletics',
    image: '/images/discipline-sports-premium.webp',
    alt: 'An athlete enjoying a balanced post-training meal with paneer, rice, vegetables and water',
    description: 'Performance nutrition for youth and competitive athletes competing at state, national, and international championships.',
    tags: ['Youth Athletes', 'Competition Prep', 'Training & Fuelling', 'Recovery Strategy', 'Hydration Plans', 'Body Composition'],
    href: links.sports,
    cta: 'Explore Sports Nutrition',
    meta: 'National & Global Athletes'
  }
];

function Pill({href,children,light=false}:{href:string;children:React.ReactNode;light?:boolean}){return <a className={'pill '+(light?'pill-light':'')} href={href}>{children}<ArrowUpRight size={17} aria-hidden="true"/></a>}
export default function Home(){const [booking,setBooking]=useState(false);const [slide,setSlide]=useState(0);const [marqueePaused,setMarqueePaused]=useState(false);const [paused,setPaused]=useState(false);const [hover,setHover]=useState(false);const [scrolled,setScrolled]=useState(false);const [navSurface,setNavSurface]=useState(false);const [menu,setMenu]=useState(false);const [services,setServices]=useState(false);const [reduced,setReduced]=useState(false);const [review,setReview]=useState(0);const touch=useRef({x:0,y:0});const menuRef=useRef<HTMLButtonElement>(null);
useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setReduced(media.matches);sync();media.addEventListener('change',sync);const scroll=()=>{setScrolled(window.scrollY>100);setNavSurface(window.scrollY>40);};scroll();window.addEventListener('scroll',scroll,{passive:true});const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('[data-reveal]').forEach(el=>{if(el.getBoundingClientRect().top>window.innerHeight&&!media.matches)el.classList.add('reveal-ready');observer.observe(el)});return()=>{media.removeEventListener('change',sync);window.removeEventListener('scroll',scroll);observer.disconnect();}},[]);
useEffect(()=>{if(paused||hover||reduced)return;const id=setInterval(()=>{if(!document.hidden)setSlide(s=>(s+1)%3)},6500);return()=>clearInterval(id)},[paused,hover,reduced,slide]);
useEffect(()=>{if(!menu)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[menu]);
const change=(n:number)=>{setSlide((n+3)%3);setPaused(true)};const close=()=>{setMenu(false);menuRef.current?.focus()};
const reviews=[{quote:'Consulted Meenu for severe acidity and gut issues. She gave a tailor-made 12-week plan around my preferences, the changes were minimal but the results were remarkable. Worth every rupee.',name:'Shobha Manoharan',detail:'Gut Health · Chennai'},{quote:'Meenu is a highly competent nutritionist, who has the ability to convey complex information into education material that patients can understand and will endeavour to comply with.\n\nMeenu\'s knowledge in the field is outstanding and its relationship with exercise has been beneficial.\n\nWe were very impressed with her depth of knowledge in adolescent nutrition and its direct relation to athletic performance. We have applied her frameworks with great effect in our adolescent population.',name:'Vijay Vallabh',detail:'Wellington Sports Medicine, New Zealand'},...moreReviews];
return <><Experience menuOpen={menu||booking}/>{booking&&<BookingModal onClose={()=>setBooking(false)}/>}<a href="#main" className="skip">Skip to content</a><header className={'navbar '+(scrolled?'compact ':'')+(navSurface?'nav-surface ':'')+(menu?'nav-menu-open':'')}><a href="#" aria-label="Pragmatic Nutrition home" className="brand"><img src="/images/logo.png" alt="Pragmatic Nutrition" width="150" height="61"/></a><nav aria-label="Main navigation" className="desktop-nav"><a href="#" aria-current="page">Home</a><a href={navLinks.about}>About Meenu</a><a href={navLinks.gut}>Gut Health Nutrition</a><a href={navLinks.sports}>Sports Nutrition</a><div className="dropdown" onMouseEnter={()=>setServices(true)} onMouseLeave={()=>setServices(false)} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setServices(false)}} onKeyDown={e=>{if(e.key==='Escape')setServices(false)}}><button aria-expanded={services} aria-controls="services" onClick={()=>setServices(!services)}>Nutrition Services <ChevronDown size={13}/></button>{services&&<div id="services" className="dropdown-panel">{extraServices.map(([title,path])=><a key={path} href={base+path}>{title}</a>)}</div>}</div><a href={base+'/blog'}>Blog</a><a href={navLinks.contact}>Contact Us</a></nav><div className="nav-actions"><button className="pill booking-trigger" onClick={()=>{setMenu(false);setBooking(true)}}>Book now<ArrowUpRight size={17} aria-hidden="true"/></button><button ref={menuRef} className="menu-toggle circle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} aria-controls="mobile-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
{menu&&<div id="mobile-menu" className="mobile-menu" data-lenis-prevent role="dialog" aria-modal="true" aria-label="Navigation menu" onKeyDown={e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const focusable=e.currentTarget.querySelectorAll<HTMLAnchorElement|HTMLButtonElement>('a,button');const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><button autoFocus className="circle mobile-close" aria-label="Close navigation" onClick={close}><X/></button><a href="#" aria-current="page" onClick={()=>{close();requestAnimationFrame(()=>window.dispatchEvent(new Event('pragmatic:top')))}}>Home</a><a href={navLinks.about}>About Meenu</a><a href={navLinks.gut}>Gut Health Nutrition</a><a href={navLinks.sports}>Sports Nutrition</a><div className="mobile-service-group"><button className="mobile-services-toggle" aria-expanded={services} aria-controls="mobile-services" onClick={()=>setServices(!services)}>Nutrition Services <ChevronDown size={20}/></button>{services&&<div id="mobile-services">{extraServices.map(([title,path])=><a className="mobile-secondary" key={path} href={base+path}>{title}</a>)}</div>}</div><a href={base+'/blog'}>Blog</a><a href={navLinks.contact}>Contact Us</a><button className="pill booking-trigger" onClick={()=>{setMenu(false);setBooking(true)}}>Book now<ArrowUpRight size={17} aria-hidden="true"/></button></div>}
<main id="main"><section className="hero" aria-label="Nutrition highlights" aria-roledescription="carousel" tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();change(slide+1)}if(e.key==='ArrowLeft'){e.preventDefault();change(slide-1)}}} onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)} onFocus={()=>setHover(true)} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setHover(false)}} onTouchStart={e=>touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY}} onTouchEnd={e=>{const dx=touch.current.x-e.changedTouches[0].clientX;const dy=touch.current.y-e.changedTouches[0].clientY;if(Math.abs(dx)>40&&Math.abs(dx)>Math.abs(dy))change(slide+(dx>0?1:-1))}}>
{slides.map((s,i)=><div className={'slide '+(slide===i?'active ':'')+(i===0?'practitioner-slide':i===1?'gut-care-slide':'')} key={s.image} aria-hidden={slide!==i} inert={slide!==i}><img className={'hero-image '+(i===2?'sports-hero-image':'food-hero-image')} src={['/images/consultation-hero-premium.webp','/images/gut-nourishment-hero.webp','/images/sports-hero-premium.webp'][i]} alt={s.alt} fetchPriority={i===0?'high':'auto'}/><div className="hero-shade"/><div className="hero-content">{i===0?<h1>{s.title}</h1>:<h2>{s.title}</h2>}<p className="hero-description">{s.description}</p><Pill href={s.href} light>{s.cta}</Pill></div></div>)}
<div className="hero-bottom"><div className="slider-controls"><div className="dots">{slides.map((s,i)=><button key={s.image} aria-label={'Show '+['personalised nutrition with Meenu','gut health','sports nutrition'][i]+' slide'} aria-pressed={slide===i} className={slide===i?'selected':''} onClick={()=>change(i)}><span/></button>)}</div><button className="circle" aria-label={paused||reduced?'Play slideshow':'Pause slideshow'} onClick={()=>{setPaused(!(paused||reduced));if(reduced)setReduced(false)}}>{paused||reduced?<Play size={15}/>:<Pause size={15}/>}</button><span className="control-divider"/><button className="circle" aria-label="Previous slide" onClick={()=>change(slide-1)}><ArrowLeft size={18}/></button><button className="circle" aria-label="Next slide" onClick={()=>change(slide+1)}><ArrowRight size={18}/></button></div></div></section>
<div className={'nutrition-marquee '+(marqueePaused?'is-paused':'')}><div className="nutrition-marquee-window"><div className="nutrition-marquee-track">{[0,1].map(copy=><div className="nutrition-marquee-group" key={copy} aria-hidden={copy===1?true:undefined}>{['Good science','Real food','Gut health','Sports nutrition','Built around you','Everyday wellbeing'].map(phrase=><span className="nutrition-marquee-item" key={phrase}><span className="marquee-flower" aria-hidden="true">✳</span>{phrase}</span>)}</div>)}</div></div><button className="marquee-control" onClick={()=>setMarqueePaused(v=>!v)} aria-label={marqueePaused?'Play nutrition marquee':'Pause nutrition marquee'}>{marqueePaused?<Play size={13}/>:<Pause size={13}/>}</button></div>
<section id="disciplines" className="disciplines section"><div className="discipline-heading" data-reveal><h2>Two Core Disciplines<br/>of <em>Practice</em></h2><p className="section-description">Personalised nutrition for better digestion, training, and everyday health.</p></div><div className="discipline-grid">{disciplinesData.map(d=><article id={d.id} className="discipline discipline-card" key={d.id} data-reveal><div className="discipline-photo-frame"><img src={d.image} alt={d.alt} loading="lazy" width="1000" height="667"/><span className="discipline-photo-tag">{d.category} · {d.number}</span><a href={d.href} className="discipline-photo-arrow circle" aria-label={'Learn more about '+d.title}><ArrowUpRight size={18}/></a></div><div className="discipline-card-body"><div className="discipline-card-header"><span className="discipline-kicker">{d.subtitle}</span><h3>{d.title}</h3></div><p className="discipline-description">{d.description}</p><div className="discipline-tags-wrap"><span className="discipline-tags-label">Key focus areas</span><div className="discipline-tags">{d.tags.map(tag=><span key={tag} className="discipline-tag">{tag}</span>)}</div></div><div className="discipline-card-footer"><Pill href={d.href}>{d.cta}</Pill><span className="discipline-card-meta"><span className="discipline-card-meta-dot" aria-hidden="true"/>{d.meta}</span></div></div></article>)}</div></section>
<PracticeIntroduction/><section className="founder section" id="about"><div className="founder-image photo-frame" data-reveal><img src="/images/meenu.jpg" alt="Meenu Balaji, founder and clinical nutritionist" loading="lazy" width="800" height="997"/></div><div className="founder-copy" data-reveal><h2>Meet<br/><em>Meenu Balaji.</em></h2><p className="section-description">Your clinical nutritionist, bringing expertise with a human touch.</p><p className="founder-intro">“You’re not failing at nutrition.<br/>You’re struggling to apply it consistently.”</p><p>Most people who work with me already know what they should be doing. Yet gut symptoms keep returning, children’s food and behaviour feel overwhelming, or training results don’t match effort.</p><p>I’m Meenu Balaji, a clinical nutritionist in India with 14+ years of clinical practice across gut health, child nutrition, and sports nutrition. I specialise in closing the gap between knowing and doing, using science, behaviour change, and realistic food strategies.</p><p>I’m a certified peer reviewer for European Journal of Nutrition and hold ICAR JRF and UGC NET JRF.</p><p>Pragmatic Nutrition is built for real life: non-extreme, flexible, and focused on long-term outcomes rather than quick fixes.</p><div className="signature"><h3>Meenu Balaji</h3><p>M.H.Sc, Food Science & Nutrition<br/>Founder, Pragmatic Nutrition</p></div><Pill href={links.about}>Meet Meenu</Pill></div></section>
<FullApproach/><AthleteStories/><AwardFeature/>
<section className="testimonials section" id="testimonials"><div className="stories-heading" data-reveal><h2>Real people.<br/><em>Personal progress.</em></h2><p className="section-description">First-hand experiences of making nutrition work in real life.</p><div className="stories-rating"><strong>4.9<span>/ 5</span></strong><span className="stories-stars" aria-label="5 stars">★★★★★</span><span>4500+ clients</span></div></div><div className="story-panel" data-reveal>
  <div className="story-top-stack">{reviews.map((r,i)=><div key={r.name} className={'story-panel-top '+(review!==i?'story-slide-inactive':'')} aria-hidden={review!==i} inert={review!==i}><span>CLIENT STORY — {String(i+1).padStart(2,'0')}</span><span className="story-topic">{r.detail.split(' · ')[0]}</span></div>)}</div>
  <div className="story-quote-stack" aria-live="polite" aria-atomic="true">{reviews.map((r,i)=><div key={r.name} className={'story-quote '+(r.quote.length>350?'story-quote-long ':'')+(review!==i?'story-slide-inactive':'')} aria-hidden={review!==i} inert={review!==i}><span className="story-quote-mark" aria-hidden="true">“</span><blockquote tabIndex={review===i?0:-1} aria-label={"Testimonial from "+r.name} data-lenis-prevent>{r.quote}</blockquote></div>)}</div>
  <div className="story-panel-bottom"><div className="story-author-stack">{reviews.map((r,i)=><div key={r.name} className={'story-author '+(review!==i?'story-slide-inactive':'')} aria-hidden={review!==i} inert={review!==i}><span className="story-initials" aria-hidden="true">{r.name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><div><p>{r.name}</p><span>{r.detail}</span></div></div>)}</div><div className="story-navigation"><button className="circle" aria-label="Previous testimonial" onClick={()=>setReview(current=>(current-1+reviews.length)%reviews.length)}><ArrowLeft size={18}/></button><span>{String(review+1).padStart(2,'0')} <span>/ {String(reviews.length).padStart(2,'0')}</span></span><button className="circle" aria-label="Next testimonial" onClick={()=>setReview(current=>(current+1)%reviews.length)}><ArrowRight size={18}/></button></div></div>
</div><div className="stories-bottom"><div className="story-dots">{reviews.map((r,i)=><button key={r.name} aria-label={'Show testimonial from '+r.name} aria-pressed={review===i} onClick={()=>setReview(i)}><span/></button>)}</div><p>Individual experiences. Results vary from person to person.</p></div></section>

<GettingStarted/><GutChecker/><FrequentlyAskedQuestions/><section className="invitation section" id="contact" data-reveal><h2>Let’s find what<br/>works <em>for you.</em></h2><p>No perfect diets. Just a practical place to begin.</p><Pill href={links.contact}>Book a free discovery call</Pill></section>
</main><footer className="footer" id="footer" data-reveal><ExtendedFooter/></footer>
<WhatsAppWidget/><button className={'back-top circle '+(scrolled?'visible':'')} aria-label="Back to top" tabIndex={scrolled?0:-1} onClick={()=>window.dispatchEvent(new Event('pragmatic:top'))}><ArrowUp size={21}/></button></>}
