'use client';
import { useEffect, useRef, useState } from 'react';
import { Experience } from './experience';
import { WhatsAppWidget } from './whatsapp';
import { PracticeIntroduction, AthleteStories, GutChecker, FullApproach, GettingStarted, AwardFeature, FrequentlyAskedQuestions, ExtendedFooter, moreReviews, extraServices } from './content';
import { ArrowUpRight, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Menu, X, ChevronDown, Pause, Play } from 'lucide-react';
const base='';
const links={gut:'#gut',sports:'#sports',about:'#about',contact:'#contact'};
const navLinks={gut:'/best-gut-health-nutritionist-india',sports:'/sports-nutritionist-india',about:'/about-meenu-balaji-nutritionist',contact:'/contact-us'};
const slides=[{image:'hero',label:'Personalised nutrition. Real life.',title:<>Eat well.<br/>Live <em>fully.</em></>,description:'Nutrition that works with your body, your food, and the life you actually live.',cta:'Find your starting point',href:links.contact,alt:'An Indian meal with chapati, dal and vegetables on a sunlit stone table'},{image:'gut',label:'A little more ease. Every day.',title:<>Good health.<br/>From <em>within.</em></>,description:'Understand your digestive symptoms with a nutrition plan built around you.',cta:'Explore Gut Health',href:links.gut,alt:'Yogurt, oats, berries, papaya and mint on a warm stone kitchen table'},{image:'sports',label:'Fuel your ambition.',title:<>Your effort.<br/>Better <em>fuel.</em></>,description:'Personalised nutrition for training, competition, and the recovery in between.',cta:'Explore Sports Nutrition',href:links.sports,alt:'An athlete taking a recovery break with a balanced meal and water'}];
function Pill({href,children,light=false}:{href:string;children:React.ReactNode;light?:boolean}){return <a className={'pill '+(light?'pill-light':'')} href={href}>{children}<ArrowUpRight size={17} aria-hidden="true"/></a>}
export default function Home(){const [slide,setSlide]=useState(0);const [marqueePaused,setMarqueePaused]=useState(false);const [paused,setPaused]=useState(false);const [hover,setHover]=useState(false);const [scrolled,setScrolled]=useState(false);const [navSurface,setNavSurface]=useState(false);const [menu,setMenu]=useState(false);const [services,setServices]=useState(false);const [reduced,setReduced]=useState(false);const [review,setReview]=useState(0);const touch=useRef(0);const menuRef=useRef<HTMLButtonElement>(null);
useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setReduced(media.matches);sync();media.addEventListener('change',sync);const scroll=()=>{setScrolled(window.scrollY>100);setNavSurface(window.scrollY>40);};scroll();window.addEventListener('scroll',scroll,{passive:true});const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('[data-reveal]').forEach(el=>{if(el.getBoundingClientRect().top>window.innerHeight&&!media.matches)el.classList.add('reveal-ready');observer.observe(el)});return()=>{media.removeEventListener('change',sync);window.removeEventListener('scroll',scroll);observer.disconnect();}},[]);
useEffect(()=>{if(paused||hover||reduced)return;const id=setInterval(()=>{if(!document.hidden)setSlide(s=>(s+1)%3)},6500);return()=>clearInterval(id)},[paused,hover,reduced,slide]);
useEffect(()=>{if(!menu)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[menu]);
const change=(n:number)=>{setSlide((n+3)%3);setPaused(true)};const close=()=>{setMenu(false);menuRef.current?.focus()};
const reviews=[{quote:'Consulted Meenu for severe acidity and gut issues. She gave a tailor-made 12-week plan around my preferences, the changes were minimal but the results were remarkable. Worth every rupee.',name:'Shobha Manoharan',detail:'Gut Health · Chennai'},{quote:'Meenu is a highly competent nutritionist, who has the ability to convey complex information into education material that patients can understand and will endeavour to comply with.\n\nMeenu\'s knowledge in the field is outstanding and its relationship with exercise has been beneficial.\n\nWe were very impressed with her depth of knowledge in adolescent nutrition and its direct relation to athletic performance. We have applied her frameworks with great effect in our adolescent population.',name:'Vijay Vallabh',detail:'Wellington Sports Medicine, New Zealand'},...moreReviews];
return <><Experience menuOpen={menu}/><a href="#main" className="skip">Skip to content</a><header className={'navbar '+(scrolled?'compact ':'')+(navSurface?'nav-surface ':'')+(menu?'nav-menu-open':'')}><a href="#" aria-label="Pragmatic Nutrition home" className="brand"><img src="/images/logo.png" alt="Pragmatic Nutrition" width="150" height="61"/></a><nav aria-label="Main navigation" className="desktop-nav"><a href="#" aria-current="page">Home</a><a href={navLinks.about}>About Meenu</a><a href={navLinks.gut}>Gut Health Nutrition</a><a href={navLinks.sports}>Sports Nutrition</a><div className="dropdown" onMouseEnter={()=>setServices(true)} onMouseLeave={()=>setServices(false)} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setServices(false)}} onKeyDown={e=>{if(e.key==='Escape')setServices(false)}}><button aria-expanded={services} aria-controls="services" onClick={()=>setServices(!services)}>Nutrition Services <ChevronDown size={13}/></button>{services&&<div id="services" className="dropdown-panel">{extraServices.map(([title,path])=><a key={path} href={base+path}>{title}</a>)}</div>}</div><a href={base+'/blog'}>Blog</a><a href={navLinks.contact}>Contact Us</a></nav><div className="nav-actions"><Pill href={navLinks.contact}>Book now</Pill><button ref={menuRef} className="menu-toggle circle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} aria-controls="mobile-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
{menu&&<div id="mobile-menu" className="mobile-menu" data-lenis-prevent role="dialog" aria-modal="true" aria-label="Navigation menu" onKeyDown={e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const focusable=e.currentTarget.querySelectorAll<HTMLAnchorElement|HTMLButtonElement>('a,button');const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><button autoFocus className="circle mobile-close" aria-label="Close navigation" onClick={close}><X/></button><a href="#" aria-current="page" onClick={()=>{close();requestAnimationFrame(()=>window.dispatchEvent(new Event('pragmatic:top')))}}>Home</a><a href={navLinks.about}>About Meenu</a><a href={navLinks.gut}>Gut Health Nutrition</a><a href={navLinks.sports}>Sports Nutrition</a><div className="mobile-service-group"><button className="mobile-services-toggle" aria-expanded={services} aria-controls="mobile-services" onClick={()=>setServices(!services)}>Nutrition Services <ChevronDown size={20}/></button>{services&&<div id="mobile-services">{extraServices.map(([title,path])=><a className="mobile-secondary" key={path} href={base+path}>{title}</a>)}</div>}</div><a href={base+'/blog'}>Blog</a><a href={navLinks.contact}>Contact Us</a><Pill href={navLinks.contact}>Book now</Pill></div>}
<main id="main"><section className="hero" aria-label="Nutrition highlights" aria-roledescription="carousel" tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();change(slide+1)}if(e.key==='ArrowLeft'){e.preventDefault();change(slide-1)}}} onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)} onFocus={()=>setHover(true)} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setHover(false)}} onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{const delta=touch.current-e.changedTouches[0].clientX;if(Math.abs(delta)>45)change(slide+(delta>0?1:-1))}}>
{slides.map((s,i)=><div className={'slide '+(slide===i?'active':'')} key={s.image} aria-hidden={slide!==i} inert={slide!==i}><img className={'hero-image '+(i===2?'sports-hero-image':'food-hero-image')} src={'/images/'+['everyday','gut','sports'][i]+'-hero-premium.webp'} alt={s.alt} fetchPriority={i===0?'high':'auto'}/><div className="hero-shade"/><div className="hero-content">{i===0?<h1>{s.title}</h1>:<h2>{s.title}</h2>}<p className="hero-description">{s.description}</p><Pill href={s.href} light>{s.cta}</Pill></div></div>)}
<div className="hero-bottom"><div className="slider-controls"><div className="dots">{slides.map((s,i)=><button key={s.image} aria-label={'Show '+['everyday nutrition','gut health','sports nutrition'][i]+' slide'} aria-pressed={slide===i} className={slide===i?'selected':''} onClick={()=>change(i)}><span/></button>)}</div><button className="circle" aria-label={paused||reduced?'Play slideshow':'Pause slideshow'} onClick={()=>{setPaused(!(paused||reduced));if(reduced)setReduced(false)}}>{paused||reduced?<Play size={15}/>:<Pause size={15}/>}</button><span className="control-divider"/><button className="circle" aria-label="Previous slide" onClick={()=>change(slide-1)}><ArrowLeft size={18}/></button><button className="circle" aria-label="Next slide" onClick={()=>change(slide+1)}><ArrowRight size={18}/></button></div></div></section>
<div className={'nutrition-marquee '+(marqueePaused?'is-paused':'')}><div className="nutrition-marquee-window"><div className="nutrition-marquee-track">{[0,1].map(copy=><div className="nutrition-marquee-group" key={copy} aria-hidden={copy===1?true:undefined}>{['Good science','Real food','Gut health','Sports nutrition','Built around you','Everyday wellbeing'].map(phrase=><span className="nutrition-marquee-item" key={phrase}><span className="marquee-flower" aria-hidden="true">✳</span>{phrase}</span>)}</div>)}</div></div><button className="marquee-control" onClick={()=>setMarqueePaused(v=>!v)} aria-label={marqueePaused?'Play nutrition marquee':'Pause nutrition marquee'}>{marqueePaused?<Play size={13}/>:<Pause size={13}/>}</button></div>
<section id="disciplines" className="disciplines section"><div className="discipline-heading" data-reveal><h2>Two Core Disciplines<br/>of <em>Practice</em></h2><p className="section-description">Personalised nutrition for better digestion, training, and everyday health.</p></div><div className="discipline-grid"><article id="gut" className="discipline" data-reveal><a href={links.gut} className="photo-frame" aria-label="Explore Gut Health"><img src="/images/discipline-gut-premium.webp" alt="A nourishing bowl of lentils, rice, pumpkin and greens on an ivory table" loading="lazy" width="1000" height="1250"/><span className="photo-link circle"><ArrowUpRight/></span></a><div className="discipline-copy"><h3>Gut Health</h3><p>Understand what’s driving your symptoms and build a sustainable nutrition program.</p><p>Digestive enzymes. Acidity. GERD. IBS. Bloating. Constipation. SIBO & gluten intolerance.</p><Pill href={links.gut}>Explore Gut Health</Pill></div></article><article id="sports" className="discipline sports" data-reveal><a href={links.sports} className="photo-frame" aria-label="Explore Sports Nutrition"><img src="/images/discipline-sports-premium.webp" alt="An athlete enjoying a balanced post-training meal with paneer, rice, vegetables and water" loading="lazy" width="1000" height="1250"/><span className="photo-link circle"><ArrowUpRight/></span></a><div className="discipline-copy"><h3>Sports Nutrition</h3><p>Performance nutrition for athletes competing in national and international events.</p><p>Youth athletes. Competitive athletes. Training nutrition. Recovery. Competition prep.</p><Pill href={links.sports}>Explore Sports Nutrition</Pill></div></article></div></section>
<PracticeIntroduction/><section className="founder section" id="about"><div className="founder-image photo-frame" data-reveal><img src="/images/meenu.jpg" alt="Meenu Balaji, founder and clinical nutritionist" loading="lazy" width="800" height="997"/></div><div className="founder-copy" data-reveal><h2>Meet<br/><em>Meenu Balaji.</em></h2><p className="section-description">Your clinical nutritionist, bringing expertise with a human touch.</p><p className="founder-intro">“You’re not failing at nutrition.<br/>You’re struggling to apply it consistently.”</p><p>Most people who work with me already know what they should be doing. Yet gut symptoms keep returning, children’s food and behaviour feel overwhelming, or training results don’t match effort.</p><p>I’m Meenu Balaji, a clinical nutritionist in India with 14+ years of clinical practice across gut health, child nutrition, and sports nutrition. I specialise in closing the gap between knowing and doing, using science, behaviour change, and realistic food strategies.</p><p>I’m a certified peer reviewer for European Journal of Nutrition and hold ICAR JRF and UGC NET JRF.</p><p>Pragmatic Nutrition is built for real life: non-extreme, flexible, and focused on long-term outcomes rather than quick fixes.</p><div className="signature"><h3>Meenu Balaji</h3><p>M.H.Sc, Food Science & Nutrition<br/>Founder, Pragmatic Nutrition</p></div><Pill href={links.about}>Meet Meenu</Pill></div></section>
<FullApproach/><AthleteStories/><AwardFeature/>
<section className="testimonials section" id="testimonials"><div className="stories-heading" data-reveal><h2>Real people.<br/><em>Personal progress.</em></h2><p className="section-description">First-hand experiences of making nutrition work in real life.</p><div className="stories-rating"><strong>4.9<span>/ 5</span></strong><span className="stories-stars" aria-label="5 stars">★★★★★</span><span>4500+ clients</span></div></div><div className="story-panel" data-reveal><div className="story-panel-top"><span>CLIENT STORY — {String(review+1).padStart(2,'0')}</span><span className="story-topic">{reviews[review].detail.split(' · ')[0]}</span></div><div className={'story-quote '+(reviews[review].quote.length>350?'story-quote-long':'')} aria-live="polite" aria-atomic="true" key={review}><span className="story-quote-mark" aria-hidden="true">“</span><blockquote>{reviews[review].quote}</blockquote></div><div className="story-panel-bottom"><div className="story-author"><span className="story-initials" aria-hidden="true">{reviews[review].name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><div><p>{reviews[review].name}</p><span>{reviews[review].detail}</span></div></div><div className="story-navigation"><button className="circle" aria-label="Previous testimonial" onClick={()=>setReview((review-1+reviews.length)%reviews.length)}><ArrowLeft size={18}/></button><span>{String(review+1).padStart(2,'0')} <span>/ {String(reviews.length).padStart(2,'0')}</span></span><button className="circle" aria-label="Next testimonial" onClick={()=>setReview((review+1)%reviews.length)}><ArrowRight size={18}/></button></div></div></div><div className="stories-bottom"><div className="story-dots">{reviews.map((r,i)=><button key={r.name} aria-label={'Show testimonial from '+r.name} aria-pressed={review===i} onClick={()=>setReview(i)}><span/></button>)}</div><p>Individual experiences. Results vary from person to person.</p></div></section>

<GettingStarted/><GutChecker/><FrequentlyAskedQuestions/><section className="invitation section" id="contact" data-reveal><h2>Let’s find what<br/>works <em>for you.</em></h2><p>No perfect diets. Just a practical place to begin.</p><Pill href={links.contact}>Book a free discovery call</Pill></section>
</main><footer className="footer" id="footer" data-reveal><ExtendedFooter/></footer>
<WhatsAppWidget/><button className={'back-top circle '+(scrolled?'visible':'')} aria-label="Back to top" tabIndex={scrolled?0:-1} onClick={()=>window.dispatchEvent(new Event('pragmatic:top'))}><ArrowUp size={21}/></button></>}
